#!/usr/bin/env node
/* Generate src/modules/index.ts to import all module manifests and register them with module_registry */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { sync as globSync } from "glob";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..", "..");
const modulesDir = path.join(repoRoot, "src", "modules");
const outFile = path.join(repoRoot, "src", "modules", "index.ts");

const patterns = ["**/index.tsx", "**/index.ts"];
const entries = new Set();
for (const p of patterns) {
  const matches = globSync(p, { cwd: modulesDir, nodir: true });
  matches.forEach((m) => entries.add(m));
}

const lines = [];
lines.push("// Auto-generated by scripts/generate/generate_modules_index.mjs");
lines.push(
  "// Imports each module's exported manifest and registers it with the module registry.",
);
lines.push("import { registerModule } from '../module_registry';");
lines.push("");

for (const rel of Array.from(entries)
  .sort()
  .filter((p) => path.dirname(p) !== ".")) {
  const id = path.dirname(rel).replace(/\\/g, "/");
  const importPath = `./${id}/index`;
  const alias = id.split("/").join("_");
  lines.push(`import ${alias}_manifest from '${importPath}';`);
}
lines.push("");
for (const rel of Array.from(entries).sort()) {
  const id = path.dirname(rel).replace(/\\/g, "/");
  const alias = id.split("/").join("_");
  lines.push(
    `if (${alias}_manifest && ${alias}_manifest?.id) registerModule(${alias}_manifest);`,
  );
}

lines.push("");
const content = lines.join("\n");
fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, content, "utf8");
console.log("Wrote", outFile);
