// Auto-generated by scripts/generate/generate_modules_index.mjs
// Imports each module's exported manifest and registers it with the module registry.
import { registerModule } from "../module_registry";

import template_sample_manifest from "./template_sample/index";
import grandpa_helper_manifest from "./grandpa_helper/index";
import housekeeping_manifest from "./housekeeping/index";

if (template_sample_manifest && template_sample_manifest?.id) {
  registerModule(template_sample_manifest);
}
if (grandpa_helper_manifest && grandpa_helper_manifest?.id) {
  registerModule(grandpa_helper_manifest);
}
if (housekeeping_manifest && housekeeping_manifest?.id) {
  registerModule(housekeeping_manifest);
}
