import { ProtocolInput, GeneratedProtocol, IndividualProtocol, StakeholderTemplate, SuccessMetric, ContingencyPlan } from '../types/protocol';
import {
  generateMasterOverview,
  generateIndividualProtocols,
  formatIndividualProtocol,
  generateStakeholderTemplates,
  formatStakeholderTemplate,
  generateContingencyPlans,
  formatContingencyPlan,
} from './protocolGenerators';
import { generateTimeline, generateSuccessMetrics, formatSuccessMetrics } from './metricsGenerators';

/**
 * Main function to generate complete protocol document
 */
export function generateProtocol(input: ProtocolInput): GeneratedProtocol {
  // Generate all sections
  const masterOverview = generateMasterOverview(input);
  const individualProtocols = generateIndividualProtocols(input);
  const stakeholderTemplates = generateStakeholderTemplates(input);
  const timeline = generateTimeline(input);
  const successMetrics = generateSuccessMetrics(input);
  const contingencyPlans = generateContingencyPlans(input);

  // Build full document
  const fullDocument = buildFullDocument({
    masterOverview,
    individualProtocols,
    stakeholderTemplates,
    timeline,
    successMetrics,
    contingencyPlans,
  });

  return {
    masterOverview,
    individualProtocols,
    stakeholderTemplates,
    timeline: [], // Milestones are embedded in timeline string
    successMetrics,
    contingencyPlans,
    fullDocument,
  };
}

/**
 * Build complete markdown document
 */
function buildFullDocument(sections: {
  masterOverview: string;
  individualProtocols: IndividualProtocol[];
  stakeholderTemplates: StakeholderTemplate[];
  timeline: string;
  successMetrics: SuccessMetric[];
  contingencyPlans: ContingencyPlan[];
}): string {
  const today = new Date().toLocaleDateString();

  let document = `---
title: Tetrahedron Protocol - Deployment Configuration
generated: ${today}
version: 1.0
framework: Tetrahedron Protocol (Open Infrastructure)
---

`;

  // Table of Contents
  document += `# Table of Contents

1. [Master Protocol Overview](#master-protocol-overview)
2. [Individual Delivery Protocols](#individual-delivery-protocols)
3. [Stakeholder Communication Templates](#stakeholder-communication-templates)
4. [Timeline & Milestones](#timeline--milestones)
5. [Success Metrics Dashboard](#success-metrics-dashboard)
6. [Contingency Plans](#contingency-plans)

---

`;

  // Section 1: Master Overview
  document += sections.masterOverview;
  document += '\n---\n\n';

  // Section 2: Individual Protocols
  document += `# Individual Delivery Protocols

These protocols are customized for each node based on their operating system and role.

`;

  sections.individualProtocols.forEach((protocol, index) => {
    document += formatIndividualProtocol(protocol, index);
  });

  document += '\n---\n\n';

  // Section 3: Stakeholder Templates
  document += `# Stakeholder Communication Templates

Use these templates to maintain consistent communication with stakeholders.

`;

  sections.stakeholderTemplates.forEach((template, index) => {
    document += formatStakeholderTemplate(template, index);
  });

  document += '\n---\n\n';

  // Section 4: Timeline
  document += sections.timeline;
  document += '\n---\n\n';

  // Section 5: Success Metrics
  document += formatSuccessMetrics(sections.successMetrics);
  document += '\n---\n\n';

  // Section 6: Contingency Plans
  document += `# Contingency Plans

Predefined responses to common challenges.

`;

  sections.contingencyPlans.forEach((plan, index) => {
    document += formatContingencyPlan(plan, index);
  });

  // Footer
  document += `
---

## Document Usage Guidelines

1. **Review Regularly**: Review this protocol at each milestone checkpoint
2. **Adapt As Needed**: This is a living document - adjust based on what works
3. **Document Changes**: Log any modifications to protocols or timelines
4. **Celebrate Progress**: Acknowledge achievements at each milestone
5. **Seek Support**: Don't hesitate to activate contingency plans or seek help

## Emergency Contacts

- **Crisis Hotline**: 988 (Suicide & Crisis Lifeline)
- **Domestic Violence**: 1-800-799-7233 (National Domestic Violence Hotline)
- **Child Abuse**: 1-800-422-4453 (Childhelp National Child Abuse Hotline)
- **Legal Aid**: [Local legal aid contact]
- **Mental Health**: [Local mental health crisis line]

---

*Generated by the Tetrahedron Protocol Deployment Guide - ${today}*

**Framework**: Open infrastructure for distributed resilience. Free to use, modify, and distribute.  
**License**: Creative Commons Attribution 4.0  
**Learn More**: https://tetrahedron-protocol.org (documentation hub)

`;

  return document;
}

/**
 * Convert FormData to ProtocolInput
 */
export function formDataToProtocolInput(formData: Partial<import('../types/form').FormData>): ProtocolInput {
  // Extract structure type
  let structure = formData.structureType || 'general';
  if (formData.familySubType) {
    structure = `family-${formData.familySubType.replace('-', '')}`;
  } else if (formData.structureType === 'team') {
    structure = 'work-team';
  }

  // Build nodes from form data
  const nodes = (formData.nodes || []).map((node: { name: string; role: string; operatingSystem: string; age?: number }) => ({
    name: node.name,
    age: node.age,
    role: node.role,
    os: node.operatingSystem,
  }));

  // Calculate timeline
  const timelineStart = formData.timelineStart ? new Date(formData.timelineStart) : new Date();
  const timelineEnd = formData.timelineEnd ? new Date(formData.timelineEnd) : new Date(Date.now() + 30 * 24 * 60 * 60 * 1000);
  const days = Math.ceil((timelineEnd.getTime() - timelineStart.getTime()) / (1000 * 60 * 60 * 24));

  return {
    structure,
    nodes,
    currentState: formData.currentState || 'transition',
    timeline: {
      days: days > 0 ? days : 30,
      targetDate: timelineEnd.toISOString().split('T')[0],
    },
    stakeholders: formData.stakeholders?.map((s: { name: string; relationship: string }) => s.relationship || s.name) || [],
    structureType: formData.structureType,
    familySubType: formData.familySubType,
    constraints: formData.constraints || [],
    protocolNotes: formData.protocolNotes || '',
  };
}
