import type { Tetrahedron } from '@/lib/types/module';

export function validateTetrahedronStructure(tetrahedron: Tetrahedron) {
  if (!tetrahedron || !tetrahedron.vertices || tetrahedron.vertices.length !== 4) {
    throw new Error('Tetrahedron must have exactly 4 vertices');
  }

  const ids = tetrahedron.vertices.map(v => v.id);
  if (new Set(ids).size !== ids.length) {
    throw new Error('Tetrahedron vertices must be unique');
  }

  // Validate edge counts when present
  if (tetrahedron.edges && tetrahedron.edges.length > 0 && tetrahedron.edges.length !== 6) {
    // Not strictly necessary; edges may be generated by the MeshProtocol, warn in console
    console.warn('Tetrahedron edges does not have 6 entries - ensure full K4 graph');
  }

  // Validate vertex ids format (simple validation, ensure not empty)
  for (const id of ids) {
    if (!id || typeof id !== 'string' || id.trim() === '') {
      throw new Error('Tetrahedron vertex IDs must be non-empty strings');
    }
  }

  // If hub vertex is present in metadata (optional), ensure it matches a vertex id
  // For local hub data we don't use a hub_vertex_id, but edge cases may include it
}

export default validateTetrahedronStructure;
